### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by ghost** [gzdan422/prj-rev-bwfs-dasmoto#5]
https://github.com/gzdan422/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20and%20Crafts/resources/css/index.css#L1-L15

You're repeating the `font-family` in a few different selectors. 

For styles that need to be applied to multiple elements, use a single rule with multiple selectors.

```css
h1, h2, p {
  font-family: Helvetica;
}
```

Or use the universal selector `*` so the styles are applied to all elements.

```css
* {
  font-family: Helvetica;
}
```
